[package]
description = "Mommy's here to support you when running cargo~"
repository = "https://github.com/Gankra/cargo-mommy"
license = "MIT OR Apache-2.0"
name = "cargo-mommy"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
<<<<<<< HEAD
confique = { version = "0.2", default-features = false, features = ["toml"]}
dirs = "4"
rand = "0.8.5"
=======
fastrand = "1.8.0"
>>>>>>> 6ae19f83e8bb866d72392a958515b32aea1621c3
serde = { version = "1.0.151", features = ["derive"] }
toml = "0.5"
